version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: traccardb
    restart: always
    environment:
      MYSQL_DATABASE: traccardb
      MYSQL_USER: traccar
      MYSQL_PASSWORD: traccar123
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - traccar-mysql-data:/var/lib/mysql
    networks:
      - traccar-net

  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: always
    ports:
      - "8082:8082"
    environment:
      DATABASE_DRIVER: mysql
      DATABASE_URL: jdbc:mysql://traccardb:3306/traccardb
      DATABASE_USER: traccar
      DATABASE_PASSWORD: traccar123
    depends_on:
      - db
    networks:
      - traccar-net

volumes:
  traccar-mysql-data:

networks:
  traccar-net: